"""
M8 step 6 -- every table in the report, regenerated from the stored JSON.

Nothing here recomputes a model quantity.  It reads

    m8_zop.npz / m8_zop_meta.json        the ZOO-Prune reproduction + its cost
    m8_phase1.json                       the depth-wall grid
    m8_zop_diag.json                     what the score is a function of
    m8_zop_validate.json                 is the reproduction faithful
    m8_zol.json                          the LLM-level estimator and its floor

and writes reports/m8_tables.md.

Usage
    python scripts/discovery/m8_analyze.py
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from common import OUTPUT_DIR                                       # noqa: E402

TABLES = os.path.join(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),
    "reports", "m8_tables.md")

RULES = ["random", "cos_s0c", "imp", "nn4_recon", "red_s0_top8", "D4",
         "maxfusion", "zop1", "zop2", "zop4", "zop8", "oracle"]
RLABEL = {"random": "random-in-pool (20 seeds)", "cos_s0c": "`cos_s0c` (best single)",
          "imp": "`imp` (EADP importance)", "nn4_recon": "`nn4_recon`",
          "red_s0_top8": "`red_s0_top8`", "D4": "M6 D4 disagreement",
          "maxfusion": "M6 max-fusion", "zop1": "ZO-P m=1", "zop2": "ZO-P m=2",
          "zop4": "ZO-P m=4", "zop8": "ZO-P m=8", "oracle": "**oracle in pool**"}



def recompute_zol_grid(z1):
    """T10's grid, rebuilt from the stored pools + scores (CPU only).

    The producer stores each instance's pool as LOCAL indices into that
    instance's dropped set, plus the raw ZO-L scores, which is everything the
    depth metrics need.  Rebuilding here rather than trusting the producer's
    inline grid keeps the table honest if the producer's aggregation changes.
    """
    from m6_common import Dropped, load_bank
    from m8_common import (ORIENT, evaluate, rank_by_score, r_cheap_in_pool,
                           r_oracle_in_pool, r_random_in_pool)

    bank = load_bank()
    bank["n"] = len(bank["key"])
    bank["fi"] = {str(nm): j for j, nm in enumerate(bank["feature_names"])}
    dropped = Dropped(bank)
    rows = z1["rows"]

    class Sub:
        pass

    sub = Sub()
    sub.n = len(rows)
    sub.drop = [dropped.drop[r["bank_row"]] for r in rows]
    sub.tr = [dropped.tr[r["bank_row"]] for r in rows]
    sub.head = {q: [dropped.head[q][r["bank_row"]] for r in rows]
                for q in dropped.head}
    sub.head_hits = lambda j, idx, q: len(
        set(np.asarray(idx).ravel().tolist()) & sub.head[q][j])

    out = {}
    for r in (8, 16, 32):
        cell = {}
        rnd = np.stack([evaluate([r_random_in_pool(np.asarray(rw["pool"]), r, s, k)
                                  for k, rw in enumerate(rows)], sub, r)["recall"]
                        for s in range(20)])
        cell["random"] = dict(recall_mean=float(rnd.mean()),
                              mean_teacher_rank=None, median_teacher_rank=None)
        for tag in ("cos_s0c", "imp"):
            picks = [r_cheap_in_pool(bank, dropped, rw["bank_row"],
                                     np.asarray(rw["pool"]), tag, r)
                     for rw in rows]
            ev = evaluate(picks, sub, r)
            cell[tag] = dict(recall_mean=ev["recall_mean"],
                             mean_teacher_rank=ev["mean_teacher_rank"],
                             median_teacher_rank=ev["median_teacher_rank"])
        for tag, key, sign in (("zol_absdJ", "dJ", -1), ("zol_dJ", "dJ", +1),
                               ("zol_dL", "dL", -1)):
            picks = [rank_by_score(np.asarray(rw["pool"]),
                                   sign * np.asarray(rw[key]))[:r] for rw in rows]
            ev = evaluate(picks, sub, r)
            cell[tag] = dict(recall_mean=ev["recall_mean"],
                             mean_teacher_rank=ev["mean_teacher_rank"],
                             median_teacher_rank=ev["median_teacher_rank"])
        picks = [r_oracle_in_pool(sub, k, np.asarray(rw["pool"]), r)
                 for k, rw in enumerate(rows)]
        ev = evaluate(picks, sub, r)
        cell["oracle"] = dict(recall_mean=ev["recall_mean"],
                              mean_teacher_rank=ev["mean_teacher_rank"],
                              median_teacher_rank=ev["median_teacher_rank"])
        out[f"r{r}"] = cell
    return out


def load(name):
    p = os.path.join(OUTPUT_DIR, name)
    return json.load(open(p)) if os.path.exists(p) else None


def main():
    zop_meta = load("m8_zop_meta.json")
    ph = load("m8_phase1.json")
    diag = load("m8_zop_diag.json")
    val = load("m8_zop_validate.json")
    zol = load("m8_zol.json")
    L = ["# M8 — generated tables", "",
         "Regenerated by `scripts/discovery/m8_analyze.py`. Every number here is "
         "read from a stored JSON; nothing is recomputed.", ""]

    if zop_meta:
        L += ["## T1 — ZOO-Prune reproduction, gate and cost", "",
              "| item | value |", "|---|---:|",
              f"| instances | {zop_meta['n']} |",
              f"| step h | {zop_meta['h']} |",
              f"| direction budgets | {zop_meta['dirs']} |",
              f"| G-MERGER max abs diff | {zop_meta['G_MERGER']['max_abs_diff']} |",
              f"| G-MERGER bad instances | {zop_meta['G_MERGER']['n_bad']} |",
              f"| vision tower | {zop_meta['cost']['tower_ms_mean']:.0f} ms |"]
        for m, v in zop_meta["cost"]["zo_ms"].items():
            L.append(f"| ZO-P m={m} | {v['median']:.1f} ms |")
        L += ["", "B2's TTFT under the same harness is **278.6 ms** (M2 record).", ""]

    if ph:
        L += ["## T2 — candidate-pool audit (held-out 210)", "",
              "| pool | |pool| | p10 | p90 | cov@8 | yield@8 | chance | meanTR |",
              "|---|---:|---:|---:|---:|---:|---:|---:|"]
        for nm, st in ph["pool_audit"].items():
            L.append(f"| **{nm}** | {st['mean_size']:.1f} | {st['p10']:.0f} | "
                     f"{st['p90']:.0f} | {st['cov8']:.4f} | {st['yield8']:.4f} | "
                     f"{st['chance']:.4f} | {st['mean_teacher_rank']:.1f} |")
        L += ["", "`cov@8` = |pool ∩ teacher-top-8 dropped| / 8, per instance then "
              "averaged. `yield@8` = the same intersection over the slots the pool "
              "spends. `meanTR` = mean teacher rank of the pool's members.", ""]

        L += ["## T3 — the depth-wall table (the decisive one)", "",
              "Method | r | head recall@r | mean teacher rank | median teacher rank",
              "|---|---:|---:|---:|---:|"]
        for pname in ("P0", "P1", "P2", "P3", "P4"):
            for r in (8, 16, 32):
                cell = ph["grid"].get(f"{pname}|r{r}")
                if not cell:
                    continue
                for rule in RULES:
                    c = cell.get(rule)
                    if c is None:
                        continue
                    mtr = (f"{c['mean_teacher_rank']:.0f}"
                           if c.get("mean_teacher_rank") is not None else "—")
                    dtr = (f"{c['median_teacher_rank']:.0f}"
                           if c.get("median_teacher_rank") is not None else "—")
                    L.append(f"{RLABEL[rule]} | {r} | {c['recall_mean']:.4f} | "
                             f"{mtr} | {dtr} |")
                L.append("")
        L += ["Pools: P0 = all 768 dropped, P1 = `cos_s0c` top-32, P2 = `cos_s0c` "
              "top-64, P3 = the four strong proxies' own top-8 union, P4 = their "
              "top-16 union. Every rule is confined to its pool.", ""]

        L += ["## T4 — ZO-P vs the controls, paired bootstrap (held-out 210)", "",
              "contrast | Δ recall@r | 95 % CI | significant",
              "|---|---:|---|---|"]
        for key, b in ph["significance"].items():
            if "-vs-cos" in key and ("zop" in key):
                p, r, k = key.split("|")[0], key.split("|")[1], key.split("|")[2]
                if r != "r8":
                    continue
                star = " *" if (b["lo"] > 0 or b["hi"] < 0) else ""
                L.append(f"{p} {k} | {b['delta']:+.4f} | "
                         f"[{b['lo']:+.4f}, {b['hi']:+.4f}] | "
                         f"{'yes' if star else 'no'}{star} |")
        L.append("")

        g = ph["global_kept"]
        L += ["## T5 — the teacher's head surviving a 256-token set from all 1024",
              "",
              "selector | head-8 kept | head-16 kept | head-32 kept",
              "|---|---:|---:|---:|"]
        for k, v in g.items():
            L.append(f"{k} | {v['kept_head8']:.4f} | {v['kept_head16']:.4f} | "
                     f"{v['kept_head32']:.4f} |")
        L.append("")

    if diag:
        L += ["## T6 — what the ZOO-Prune score is a function of", "",
              "| m | vs teacher (all 1024) | vs teacher (dropped) | frac. positive |",
              "|---:|---:|---:|---:|"]
        for m in ("m1", "m2", "m4", "m8"):
            v = diag["D1_teacher"][m]
            L.append(f"| {m[1:]} | {v['vs_teacher_all1024']:+.4f} | "
                     f"{v['vs_teacher_dropped']:+.4f} | "
                     f"{v['frac_positive_dropped']:.3f} |")
        L += ["", "Spearman, per instance then averaged. A negative value means "
              "high ZO-P marks teacher-*unimportant* tokens.", "",
              "| cheap column | mean ρ (m=8) |", "|---|---:|"]
        for nm, v in diag["D2_cheap"]["m8"]["top_by_abs"]:
            L.append(f"| `{nm}` | {v['mean']:+.4f} |")
        d5 = diag.get("D5_cheap_vs_teacher")
        if d5:
            L += ["", "**D5 — the bar ZO-P has to clear**: each cheap column's own "
                  "rank agreement with the teacher, on the same instances, same "
                  "dropped set, same statistic (oriented so high = teacher-"
                  "critical):", "",
                  "| cheap column | ρ vs \|teacher\| (oriented) |", "|---|---:|"]
            for nm, v in sorted(d5.items(), key=lambda kv: -kv[1]["oriented_mean"])[:8]:
                L.append(f"| `{nm}` | {v['oriented_mean']:+.4f} |")
            L += ["", "ZO-P's own value is **−0.236**: it is below every column in "
                  "this list, including the one it restates.", ""]
        L += ["", "| quantity | value |", "|---|---:|"]
        for m, v in diag["D4_selection"].items():
            L.append(f"| ZO-P {m} top-256 ∩ B2's S0 | {v['overlap_with_B2_s0']:.4f} |")
        L.append("")

    if val:
        L += ["## T7 — is the reproduction faithful, and is `S ~ ||v||` real?", "",
              "| comparison | mean Spearman |", "|---|---:|"]
        for k, v in val["mean"].items():
            if k.startswith("rel_"):
                L.append(f"| {k} | {v:+.4f} |")
        L += ["", f"`scale_ratio_h1_over_h01` = "
              f"{val['mean']['scale_ratio_h1_over_h01']:.2f} — a first-order "
              "estimator would give 100.", ""]

    if zol:
        L += ["## T8 — the LLM-level estimator: per-token effect vs the quantum",
              "",
              "| k tokens zeroed | mean dJ | per token | in quanta | mean ||d logits|| | mean ||d h_last|| |",
              "|---:|---:|---:|---:|---:|---:|"]
        cal = zol["calib"]
        ks = zol["ks"]
        tulp = np.mean([2.0 ** (int(np.floor(np.log2(abs(c["J0"])))) - 7)
                        for c in cal])
        for j, k in enumerate(ks):
            m = np.mean([c["dJ"][j] for c in cal])
            L.append(f"| {k} | {m:+.4f} | {m/k:+.5f} | {m/tulp:+.3f} | "
                     f"{np.mean([c['dlogits'][j] for c in cal]):.2f} | "
                     f"{np.mean([c['dh_last'][j] for c in cal]):.3f} |")
        nd = [len(np.unique(np.round(np.abs(r["res"]["0.1"]["dJ_a"]), 6)))
              for r in zol["rows"]]
        L += ["", f"distinct values of `|dJ|` across the 32-token pool, h=0.1: "
              f"**{np.mean(nd):.1f}** per instance (min {min(nd)}, max {max(nd)})", ""]
        tulp = [2.0 ** (int(np.floor(np.log2(abs(c["J0"])))) - 7) for c in cal]
        L += ["", f"mean bf16 quantum of the response logit: "
              f"**{np.mean(tulp):.4f}** (recomputed from J0)", "",
              "| h | response | split-half ρ | ρ vs teacher | spread (sd/mean) |",
              "|---:|---|---:|---:|---:|"]
        for h in zol["h_grid"]:
            hs = [r["res"][str(h)] for r in zol["rows"]]
            for tag, rk, sk in (("dJ", "rho_J", "spread_J"),
                                ("dlogits", "rho_L", "spread_L"),
                                ("dh_last", "rho_H", "spread_H")):
                L.append(f"| {h} | {tag} | "
                         f"{np.mean([x[rk] for x in hs]):.3f} | "
                         f"{np.mean([x['rhoT_'+rk[-1]] for x in hs]):+.3f} | "
                         f"{np.mean([x[sk] for x in hs]):.4f} |")
        L.append("")

    grp = load("m8_zol_group.json")
    if grp:
        L += ["## T9 — the shared-direction / Hadamard escape hatch", "",
              f"n = {grp['n']} instances, h_rel = {grp['h_rel']}, "
              f"{grp['n_dirs']} shared directions, pool = {grp['pool']}, "
              f"mean quantum = {grp['ulp_mean']:.3f}", "",
              "| arm | mean dJ | in quanta | below half a quantum |",
              "|---|---:|---:|---:|",
              f"| zero the whole pool (control) | {grp['zero_pool']['mean']:+.3f} | "
              f"{grp['zero_pool']['in_quanta']:+.2f} | — |",
              f"| perturb the pool, shared dirs | "
              f"{grp['pool_shared'].get('mean_abs', abs(grp['pool_shared']['mean'])):.3f} | "
              f"{grp['pool_shared']['in_quanta']:.2f} | "
              f"{grp['pool_shared']['frac_below_half_quantum']*100:.0f} % |",
              f"| perturb all 768 dropped, shared dirs | "
              f"{grp['all768_shared'].get('mean_abs', abs(grp['all768_shared']['mean'])):.3f} | "
              f"{grp['all768_shared']['in_quanta']:.2f} | "
              f"{grp['all768_shared']['frac_below_half_quantum']*100:.0f} % |", ""]

    z1 = load("m8_zol_phase1.json")
    if z1:
        L += ["## T10 — ZO-L through the same Phase-1 gate (the brief's ask)", "",
              f"n = {z1['n']} held-out instances, "
              f"pool = {z1.get('pool', 32)}, "
              f"m = {z1['config']['dirs']} directions, "
              f"h_rel = {z1['config']['h']}", "",
              f"mean rho(ZO-L |dJ|, |teacher|) = **{z1['mean_rhoT_J']:+.4f}**;  "
              f"mean rho(ZO-L ‖Δ logits‖, |teacher|) = "
              f"**{z1['mean_rhoT_L']:+.4f}**;  "
              f"distinct |dJ| values per pool = {z1['mean_distinct_dJ']:.1f};  "
              f"fraction of pool tokens with dJ exactly 0 = "
              f"{z1['mean_frac_zero_dJ']:.2f}", ""]
        grid = recompute_zol_grid(z1)
        L += ["Method | r | head recall@r | mean teacher rank | median teacher rank",
              "|---|---:|---:|---:|---:|"]
        for r in (8, 16, 32):
            for k in ("random", "cos_s0c", "imp", "zol_absdJ", "zol_dJ",
                      "zol_dL", "oracle"):
                c = grid.get(f"r{r}", {}).get(k)
                if c is None:
                    continue
                mtr = (f"{c['mean_teacher_rank']:.0f}"
                       if c.get("mean_teacher_rank") is not None else "—")
                dtr = (f"{c['median_teacher_rank']:.0f}"
                       if c.get("median_teacher_rank") is not None else "—")
                L.append(f"{k} | {r} | {c['recall_mean']:.4f} | {mtr} | {dtr} |")
            L.append("")
        L += ["`zol_absdJ` ranks by descending |dJ|; `zol_dJ` by the signed value; "
              "`zol_dL` by ‖Δ logits‖. Same pool, same r, same metrics as T3. "
              "**Recomputed here from the stored per-instance pools and scores**, "
              "so the table does not depend on the producer's own aggregation.",
              ""]

    os.makedirs(os.path.dirname(TABLES), exist_ok=True)
    with open(TABLES, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"[saved] {TABLES}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
