"""
S2-C6 step 3: render the stage's tables from ``s2c6_audit.json`` as markdown.

The numbers in ``docs/scoring_search_s2c6.md`` come from here rather than from
being retyped, so a table cannot drift from the artifact it summarises. Prints to
stdout; the runner tees it to ``outputs/discovery/s2c6_tables.md``.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from s1_audit import OUT                                              # noqa: E402


def ci(v, fmt="{:+.4f}"):
    return f"{fmt.format(v['mean'])} [{fmt.format(v['lo'])}, {fmt.format(v['hi'])}]"


def seeds(v):
    return " / ".join(f"{x:+.3f}" for x in v["per_seed"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default="s2c6")
    args = ap.parse_args()
    A = json.load(open(os.path.join(OUT, f"{args.tag}_audit.json")))

    print("# S2-C6 tables\n")
    print("Generated by `s2c6_tables.py` from `%s_audit.json`. Every quantity is\n"
          "held-out (150 images) teacher Top-8 recall@256 at the validation-"
          "selected\ncheckpoint, seed-averaged over 0/1/2 unless the column says "
          "otherwise.\n" % args.tag)

    # ---------------------------------------------------------------- part A
    print("\n## Part A -- teacher-data scaling\n")
    print("| n | R@8 | R@16 | R@32 | ov256 | per-seed R@8 | init R@8 | epoch |")
    print("|---|-----|------|------|-------|--------------|----------|-------|")
    for n in sorted(int(k) for k in A["part_A"]["curve"]):
        c = A["part_A"]["curve"][str(n)]
        h = c["held_out"]
        print(f"| {n} | {h['head_recall8']:.4f} | {h['head_recall16']:.4f} | "
              f"{h['head_recall32']:.4f} | {h['overlap256']:.4f} | "
              f"{' / '.join(f'{x:.4f}' for x in c['per_seed_head_recall8'])} | "
              f"{c['init_held_out_head_recall8']:.4f} | {c['best_epoch']} |")

    print("\n| segment | delta | 95% CI | per-seed | resolved |")
    print("|---------|-------|--------|----------|----------|")
    for k, v in A["part_A"]["segments"].items():
        print(f"| {k} | {v['mean']:+.4f} | [{v['lo']:+.4f}, {v['hi']:+.4f}] | "
              f"{seeds(v)} | {v['resolved']} |")
    print(f"\n**{A['part_A']['verdict']}** -- {A['part_A']['verdict_reason']}\n")

    # ---------------------------------------------------------------- part B
    print("\n## Part B -- representation localization\n")
    print("| arm | R@8 | R@16 | ov256 | vs governing ref | 95% CI | per-seed | "
          "gov | resolved | params | init R@8 |")
    print("|-----|-----|------|-------|------------------|--------|----------|"
          "-----|----------|--------|----------|")
    rows = dict(A["part_B"]["arms"])
    if "L4" in rows:
        pass
    for a, s in rows.items():
        h, v = s["held_out"], s["vs_reference"]
        print(f"| {a} | {h['head_recall8']:.4f} | {h['head_recall16']:.4f} | "
              f"{h['overlap256']:.4f} | {v['mean']:+.4f} | "
              f"[{v['lo']:+.4f}, {v['hi']:+.4f}] | {seeds(v)} | "
              f"{s['governing_reference']} | {v['resolved']} | "
              f"{s['n_params']:,} | {s['init_held_out_head_recall8']:.4f} |")

    g = A["part_B"]["architecture_control_L4_L4_vs_L4"]
    print(f"\n**L4+L4 architecture control vs L4:** {ci(g)}, per-seed {seeds(g)}, "
          f"resolved={g['resolved']}. {A['part_B']['control_effect']}.\n")

    print("\n| arm | control | honest − wrong | 95% CI | per-seed | resolved |")
    print("|-----|---------|----------------|--------|----------|----------|")
    for a, s in list(rows.items()) + list(A["part_C"]["arms"].items()):
        for name, c in (s.get("controls") or {}).items():
            if name.startswith("SELF_CHECK"):
                continue
            v = c["honest_minus_wrong"]
            print(f"| {a} | {name} | {v['mean']:+.4f} | "
                  f"[{v['lo']:+.4f}, {v['hi']:+.4f}] | {seeds(v)} | "
                  f"{v['resolved']} |")

    # ---------------------------------------------------------------- part C
    print("\n## Part C -- query re-check\n")
    print("| arm | R@8 | R@16 | vs L4 | 95% CI | per-seed | resolved | "
          "params (query) | init R@8 |")
    print("|-----|-----|------|-------|--------|----------|----------|"
          "----------------|----------|")
    for a, s in A["part_C"]["arms"].items():
        h, v = s["held_out"], s["vs_reference"]
        print(f"| {a} | {h['head_recall8']:.4f} | {h['head_recall16']:.4f} | "
              f"{v['mean']:+.4f} | [{v['lo']:+.4f}, {v['hi']:+.4f}] | "
              f"{seeds(v)} | {v['resolved']} | "
              f"{s['n_params']:,} ({s['n_query_params']:,}) | "
              f"{s['init_held_out_head_recall8']:.4f} |")
    qs_path = os.path.join(OUT, f"{args.tag}_train_C.json")
    if os.path.exists(qs_path):
        T = json.load(open(qs_path))
        print("\nHow much of the query branch's magnitude is *per-image*? A "
              "branch that has learned a per-image constant scores ~0 on the "
              "last column, whatever its parameter count or its norm.\n")
        print("| arm | seed | query-term norm (at init) | across-image norm | "
              "across-image ratio |")
        print("|-----|------|---------------------------|-------------------|"
              "--------------------|")
        for a in ("L4+QUERY", "L4+QRY-BILIN"):
            for s in (0, 1, 2):
                k = f"full__{a}_s{s}"
                if k not in T["results"]:
                    continue
                qs = T["results"][k]["selections"]["H8"].get("query_scale_val")
                ini = (T["results"][k]["init"].get("query_scale_val") or {})
                if qs:
                    print(f"| {a} | {s} | {qs['query_term_norm_mean']:.4f} "
                          f"({ini.get('query_term_norm_mean', float('nan')):.4f}) "
                          f"| {qs['across_image_norm_mean']:.4f} "
                          f"| {100 * qs['across_image_ratio']:.2f}% |")

        print("\nDoes replacing the image's query with another image's change the "
              "score at all?\n")
        print("| arm | seed | mean abs score change | max abs score change |")
        print("|-----|------|-----------------------|----------------------|")
        for a in ("L4+QUERY", "L4+QRY-BILIN"):
            for s in (0, 1, 2):
                k = f"full__{a}_s{s}"
                if k not in T["results"]:
                    continue
                d = T["results"][k]["selections"]["H8"]["controls"].get(
                    "WRONG_QUERY_score_delta")
                if d:
                    print(f"| {a} | {s} | {d['abs_mean']:.3e} | "
                          f"{d['abs_max']:.3e} |")

    # ------------------------------------------------- query control detail
    qc_path = os.path.join(OUT, f"{args.tag}_query_control.json")
    if os.path.exists(qc_path):
        Q = json.load(open(qc_path))
        print("\nSelection-level effect of replacing the image's query "
              "(`s2c6_query_control.py`). `changed256` is the fraction of the "
              "selected 256 tokens the query actually moves.\n")
        print("| arm | seed | changed256 | head R@8 honest | wrong | delta | "
              "mean |Δscore| | max |Δscore| |")
        print("|-----|------|------------|-----------------|-------|-------|"
              "--------------|---------------|")
        for a, s in Q["arms"].items():
            for r in s["per_seed"]:
                print(f"| {a} | {r['seed']} | {r['changed256']:.4f} | "
                      f"{r['head8_honest']:.4f} | {r['head8_wrong']:.4f} | "
                      f"{r['head8_delta']:+.4f} | "
                      f"{r['abs_score_diff_mean']:.3e} | "
                      f"{r['abs_score_diff_max']:.3e} |")
            m = s["mean"]
            print(f"| **{a} mean** | | **{m['changed256']:.4f}** | "
                  f"**{m['head8_honest']:.4f}** | **{m['head8_wrong']:.4f}** | "
                  f"**{m['head8_delta']:+.4f}** | | |")

    # -------------------------------------------------------------- verdicts
    print("\n## Verdicts\n")
    for k, v in A["verdicts"]["flags"].items():
        print(f"- **{k}**: {v}")
    print(f"\n> {A['headline']}\n")
    for k, v in A["verdicts"]["reasons"].items():
        print(f"- `{k}` -- {v}")

    d = A["deployable_gate"]
    print(f"\n## Downstream gate\n\n{d['rule']}\n")
    print(f"- best arm: **{d['best_arm']}** at {d['best_held_out_head_recall8']:.4f}")
    print(f"- reaching 0.82: {d['reaches_0.82'] or 'none'}")
    print(f"- clearing every condition: {d['clears'] or 'none'}")
    print(f"- downstream_run: **{d['downstream_run']}** -- {d['note']}")

    print(f"\n## Consistency\n")
    c = A["consistency"]
    print(f"- Part A (n=240) vs Part B (L4) max |per-image diff| = "
          f"{c['partA_240_equals_partB_L4_max_abs_diff']:.2e} "
          f"(identical: {c['identical']})")
    print(f"- L4+QUERY untrained identity vs L4, max |score diff| per seed = "
          f"{c['l4_query_init_identity_max_abs_diff']}")


if __name__ == "__main__":
    main()
